openai_api_type: 'azure'
openai_api_base: 'https://your-project-name.openai.azure.com/'
openai_api_version: '2023-05-15'
deployment_name: 'your-deployment-nam'
index_name: 'your-index-name'
engine: 'embeddings-ada-002'
pinecone_key_file: pinecone_key.txt
azure_openai_key_file: azure_openai_key.txt
min_chunk_len: 200
batch_size: 5
